//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Northwind.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;id&quot;: &quot;1&quot;,
        ///	&quot;name&quot;: &quot;This is my test policy&quot;,
        ///	&quot;description&quot;: &quot;Hello World Policy&quot;,
        ///	&quot;rules&quot;: [{
        ///			&quot;resource&quot;: [&quot;contract&quot;],
        ///			&quot;action&quot;: [&quot;contract:list&quot;, &quot;contract:view&quot;],
        ///			&quot;effect&quot;: &quot;allow&quot;,
        ///			&quot;condition&quot;: {
        ///				&quot;bool&quot;: {
        ///					&quot;user:isEmployee&quot;: &quot;true&quot;
        ///				}
        ///			}
        ///		},
        ///		{
        ///			&quot;resource&quot;: [&quot;contract&quot;],
        ///			&quot;action&quot;: [&quot;contract:list&quot;, &quot;contract:view&quot;],
        ///			&quot;effect&quot;: &quot;allow&quot;,
        ///			&quot;condition&quot;: {
        ///				&quot;stringEquals&quot;: {
        ///					&quot;user:email&quot;: &quot;saryal@xylontech.com&quot;
        ///				}
        ///			}
        ///		},
        ///		{
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string policy2 {
            get {
                return ResourceManager.GetString("policy2", resourceCulture);
            }
        }
    }
}
