//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.Core.Internationalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Northwind.Core.Internationalization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;id&quot;: &quot;21f1b740-c6b4-4a48-8db4-5a3a591c3e41&quot;,
        ///	&quot;name&quot;: &quot;This is my test policy&quot;,
        ///	&quot;description&quot;: &quot;Hello World Policy&quot;,
        ///	&quot;rules&quot;: [{
        ///			&quot;resource&quot;: [&quot;contract&quot;],
        ///			&quot;action&quot;: [&quot;contract:list&quot;, &quot;contract:view&quot;],
        ///			&quot;effect&quot;: &quot;allow&quot;,
        ///			&quot;condition&quot;: {
        ///				&quot;bool&quot;: {
        ///					&quot;user:isEmployee&quot;: &quot;true&quot;
        ///				}
        ///			}
        ///		},
        ///		{
        ///			&quot;resource&quot;: [&quot;contract&quot;],
        ///			&quot;action&quot;: [&quot;contract:list&quot;, &quot;contract:view&quot;],
        ///			&quot;effect&quot;: &quot;allow&quot;,
        ///			&quot;condition&quot;: {
        ///				&quot;stringEquals&quot;: {
        ///					&quot;user:email&quot;: &quot;saryal@xylonte [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SimplePolicyExample {
            get {
                return ResourceManager.GetString("SimplePolicyExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:1,&quot;username&quot;:&quot;cgallo0@discuz.net&quot;,&quot;displayname&quot;:&quot;Colet Gallo&quot;,&quot;phonenumber&quot;:&quot;336-941-5032&quot;,&quot;status&quot;:&quot;Active&quot;,&quot;group&quot;:&quot;Executives&quot;},
        ///{&quot;id&quot;:2,&quot;username&quot;:&quot;rwinchcum1@howstuffworks.com&quot;,&quot;displayname&quot;:&quot;Rikki Winchcum&quot;,&quot;phonenumber&quot;:&quot;516-572-3544&quot;,&quot;status&quot;:&quot;Active&quot;,&quot;group&quot;:&quot;Executives&quot;},
        ///{&quot;id&quot;:3,&quot;username&quot;:&quot;gschutze2@shareasale.com&quot;,&quot;displayname&quot;:&quot;Galen Schutze&quot;,&quot;phonenumber&quot;:&quot;190-863-8977&quot;,&quot;status&quot;:&quot;Active&quot;,&quot;group&quot;:&quot;Operations&quot;},
        ///{&quot;id&quot;:4,&quot;username&quot;:&quot;phumphrys3@ustream.tv&quot;,&quot;displayname&quot;:&quot;Pearle Humphrys [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SimpleUserList {
            get {
                return ResourceManager.GetString("SimpleUserList", resourceCulture);
            }
        }
    }
}
