// <auto-generated />
namespace AutoCare.Product.Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class engine_transmission : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(engine_transmission));
        
        string IMigrationMetadata.Id
        {
            get { return "201610181004483_engine_transmission"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
