// <auto-generated />
namespace AutoCare.Product.Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class remove_PowerOutput : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_PowerOutput));
        
        string IMigrationMetadata.Id
        {
            get { return "201610181210156_remove_PowerOutput"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
