// <auto-generated />
namespace AutoCare.Product.Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DriveType_MfrBodyCode_WheelBase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DriveType_MfrBodyCode_WheelBase));
        
        string IMigrationMetadata.Id
        {
            get { return "201609290857126_DriveType_MfrBodyCode_WheelBase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
