// <auto-generated />
namespace AutoCare.Product.Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class remove_FuelDeliveryConfigCount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_FuelDeliveryConfigCount));
        
        string IMigrationMetadata.Id
        {
            get { return "201610190545190_remove_FuelDeliveryConfigCount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
