// <auto-generated />
namespace AutoCare.Product.Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ColumnrenamedToDirectoryPath : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ColumnrenamedToDirectoryPath));
        
        string IMigrationMetadata.Id
        {
            get { return "201608121629235_ColumnrenamedToDirectoryPath"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
