//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCare.Product.Web.Personify.ImsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://TIMSSSSO/imswebservice/", ConfigurationName="Personify.ImsService.IMServiceSoap")]
    public interface IMServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TIMSSSSO/imswebservice/IMSCustomerRoleGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AutoCare.Product.Web.Personify.ImsService.IMSCustomerRoleGetResult IMSCustomerRoleGet(string vendorUsername, string vendorPassword, string customerToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TIMSSSSO/imswebservice/IMSCustomerRoleGet", ReplyAction="*")]
        System.Threading.Tasks.Task<AutoCare.Product.Web.Personify.ImsService.IMSCustomerRoleGetResult> IMSCustomerRoleGetAsync(string vendorUsername, string vendorPassword, string customerToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TIMSSSSO/imswebservice/IMSCustomerRoleGetByTimssCustomerId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AutoCare.Product.Web.Personify.ImsService.IMSCustomerRoleGetResult IMSCustomerRoleGetByTimssCustomerId(string vendorUsername, string vendorPassword, string TimssCustomerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TIMSSSSO/imswebservice/IMSCustomerRoleGetByTimssCustomerId", ReplyAction="*")]
        System.Threading.Tasks.Task<AutoCare.Product.Web.Personify.ImsService.IMSCustomerRoleGetResult> IMSCustomerRoleGetByTimssCustomerIdAsync(string vendorUsername, string vendorPassword, string TimssCustomerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TIMSSSSO/imswebservice/IMSRoleCustomersGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AutoCare.Product.Web.Personify.ImsService.IMSRoleCustomersGetResult IMSRoleCustomersGet(string vendorUsername, string vendorPassword, string RoleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TIMSSSSO/imswebservice/IMSRoleCustomersGet", ReplyAction="*")]
        System.Threading.Tasks.Task<AutoCare.Product.Web.Personify.ImsService.IMSRoleCustomersGetResult> IMSRoleCustomersGetAsync(string vendorUsername, string vendorPassword, string RoleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TIMSSSSO/imswebservice/IMSVendorRolesGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AutoCare.Product.Web.Personify.ImsService.IMSVendorRolesGetResult IMSVendorRolesGet(string vendorUsername, string vendorPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TIMSSSSO/imswebservice/IMSVendorRolesGet", ReplyAction="*")]
        System.Threading.Tasks.Task<AutoCare.Product.Web.Personify.ImsService.IMSVendorRolesGetResult> IMSVendorRolesGetAsync(string vendorUsername, string vendorPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TIMSSSSO/imswebservice/IMSCustomerWebRoleGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AutoCare.Product.Web.Personify.ImsService.IMSCustomerRoleGetResult IMSCustomerWebRoleGet(string vendorUsername, string vendorPassword, string customerToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TIMSSSSO/imswebservice/IMSCustomerWebRoleGet", ReplyAction="*")]
        System.Threading.Tasks.Task<AutoCare.Product.Web.Personify.ImsService.IMSCustomerRoleGetResult> IMSCustomerWebRoleGetAsync(string vendorUsername, string vendorPassword, string customerToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TIMSSSSO/imswebservice/IMSVendorWebRolesGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AutoCare.Product.Web.Personify.ImsService.IMSVendorRolesGetResult IMSVendorWebRolesGet(string vendorUsername, string vendorPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TIMSSSSO/imswebservice/IMSVendorWebRolesGet", ReplyAction="*")]
        System.Threading.Tasks.Task<AutoCare.Product.Web.Personify.ImsService.IMSVendorRolesGetResult> IMSVendorWebRolesGetAsync(string vendorUsername, string vendorPassword);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TIMSSSSO/imswebservice/")]
    public partial class IMSCustomerRoleGetResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Role[] customerRolesField;
        
        private string[] errorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Role[] CustomerRoles {
            get {
                return this.customerRolesField;
            }
            set {
                this.customerRolesField = value;
                this.RaisePropertyChanged("CustomerRoles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TIMSSSSO/imswebservice/")]
    public partial class Role : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TIMSSSSO/imswebservice/")]
    public partial class VendorRole : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string roleIdField;
        
        private string roleDescriptionField;
        
        private bool isActiveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RoleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
                this.RaisePropertyChanged("RoleId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RoleDescription {
            get {
                return this.roleDescriptionField;
            }
            set {
                this.roleDescriptionField = value;
                this.RaisePropertyChanged("RoleDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
                this.RaisePropertyChanged("IsActive");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TIMSSSSO/imswebservice/")]
    public partial class IMSVendorRolesGetResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VendorRole[] vendorRolesField;
        
        private string[] errorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public VendorRole[] VendorRoles {
            get {
                return this.vendorRolesField;
            }
            set {
                this.vendorRolesField = value;
                this.RaisePropertyChanged("VendorRoles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TIMSSSSO/imswebservice/")]
    public partial class RoleCustomer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string roleIdField;
        
        private string timssCustomerIdField;
        
        private string searchNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RoleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
                this.RaisePropertyChanged("RoleId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TimssCustomerId {
            get {
                return this.timssCustomerIdField;
            }
            set {
                this.timssCustomerIdField = value;
                this.RaisePropertyChanged("TimssCustomerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SearchName {
            get {
                return this.searchNameField;
            }
            set {
                this.searchNameField = value;
                this.RaisePropertyChanged("SearchName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TIMSSSSO/imswebservice/")]
    public partial class IMSRoleCustomersGetResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RoleCustomer[] roleCustomersField;
        
        private string[] errorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public RoleCustomer[] RoleCustomers {
            get {
                return this.roleCustomersField;
            }
            set {
                this.roleCustomersField = value;
                this.RaisePropertyChanged("RoleCustomers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMServiceSoapChannel : AutoCare.Product.Web.Personify.ImsService.IMServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MServiceSoapClient : System.ServiceModel.ClientBase<AutoCare.Product.Web.Personify.ImsService.IMServiceSoap>, AutoCare.Product.Web.Personify.ImsService.IMServiceSoap {
        
        public MServiceSoapClient() {
        }
        
        public MServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AutoCare.Product.Web.Personify.ImsService.IMSCustomerRoleGetResult IMSCustomerRoleGet(string vendorUsername, string vendorPassword, string customerToken) {
            return base.Channel.IMSCustomerRoleGet(vendorUsername, vendorPassword, customerToken);
        }
        
        public System.Threading.Tasks.Task<AutoCare.Product.Web.Personify.ImsService.IMSCustomerRoleGetResult> IMSCustomerRoleGetAsync(string vendorUsername, string vendorPassword, string customerToken) {
            return base.Channel.IMSCustomerRoleGetAsync(vendorUsername, vendorPassword, customerToken);
        }
        
        public AutoCare.Product.Web.Personify.ImsService.IMSCustomerRoleGetResult IMSCustomerRoleGetByTimssCustomerId(string vendorUsername, string vendorPassword, string TimssCustomerId) {
            return base.Channel.IMSCustomerRoleGetByTimssCustomerId(vendorUsername, vendorPassword, TimssCustomerId);
        }
        
        public System.Threading.Tasks.Task<AutoCare.Product.Web.Personify.ImsService.IMSCustomerRoleGetResult> IMSCustomerRoleGetByTimssCustomerIdAsync(string vendorUsername, string vendorPassword, string TimssCustomerId) {
            return base.Channel.IMSCustomerRoleGetByTimssCustomerIdAsync(vendorUsername, vendorPassword, TimssCustomerId);
        }
        
        public AutoCare.Product.Web.Personify.ImsService.IMSRoleCustomersGetResult IMSRoleCustomersGet(string vendorUsername, string vendorPassword, string RoleId) {
            return base.Channel.IMSRoleCustomersGet(vendorUsername, vendorPassword, RoleId);
        }
        
        public System.Threading.Tasks.Task<AutoCare.Product.Web.Personify.ImsService.IMSRoleCustomersGetResult> IMSRoleCustomersGetAsync(string vendorUsername, string vendorPassword, string RoleId) {
            return base.Channel.IMSRoleCustomersGetAsync(vendorUsername, vendorPassword, RoleId);
        }
        
        public AutoCare.Product.Web.Personify.ImsService.IMSVendorRolesGetResult IMSVendorRolesGet(string vendorUsername, string vendorPassword) {
            return base.Channel.IMSVendorRolesGet(vendorUsername, vendorPassword);
        }
        
        public System.Threading.Tasks.Task<AutoCare.Product.Web.Personify.ImsService.IMSVendorRolesGetResult> IMSVendorRolesGetAsync(string vendorUsername, string vendorPassword) {
            return base.Channel.IMSVendorRolesGetAsync(vendorUsername, vendorPassword);
        }
        
        public AutoCare.Product.Web.Personify.ImsService.IMSCustomerRoleGetResult IMSCustomerWebRoleGet(string vendorUsername, string vendorPassword, string customerToken) {
            return base.Channel.IMSCustomerWebRoleGet(vendorUsername, vendorPassword, customerToken);
        }
        
        public System.Threading.Tasks.Task<AutoCare.Product.Web.Personify.ImsService.IMSCustomerRoleGetResult> IMSCustomerWebRoleGetAsync(string vendorUsername, string vendorPassword, string customerToken) {
            return base.Channel.IMSCustomerWebRoleGetAsync(vendorUsername, vendorPassword, customerToken);
        }
        
        public AutoCare.Product.Web.Personify.ImsService.IMSVendorRolesGetResult IMSVendorWebRolesGet(string vendorUsername, string vendorPassword) {
            return base.Channel.IMSVendorWebRolesGet(vendorUsername, vendorPassword);
        }
        
        public System.Threading.Tasks.Task<AutoCare.Product.Web.Personify.ImsService.IMSVendorRolesGetResult> IMSVendorWebRolesGetAsync(string vendorUsername, string vendorPassword) {
            return base.Channel.IMSVendorWebRolesGetAsync(vendorUsername, vendorPassword);
        }
    }
}
